import { defineConfig } from "vitepress";
// Generated by TypeDoc (`npm run docs:api`, folded into `dev`/`build`) from the SDK's PUBLIC
// JSDoc — the API reference under `/api/`. `docs/api/` is a build artifact (gitignored) and is
// re-swept by `guard:docs` for wire/crypto/RE leaks before every build.
import typedocSidebar from "../api/typedoc-sidebar.json";

/**
 * VitePress config for the HOST-FACING docs site.
 *
 * ⚠️ PUBLICATION GUARD — this site publishes `docs/` and nothing else.
 * This is a self-contained npm project (its own package.json here in `docs/`, kept out of the SDK's
 * dependency tree). The build runs with this folder as cwd (`npm -C docs run build`), so the site root
 * (srcDir) is THIS folder — never add a `srcDir`/rewrite that reaches the parent. The remaining risk
 * is a PUBLIC symbol's JSDoc carrying wire or crypto detail onto the generated API pages, which is
 * what `guard:docs` re-sweeps for.
 */
/**
 * The site is served from the domain root (`mega-yfue.github.io`), so `/` is the default. Override via
 * DOCS_BASE for any other host — a project Pages site under `/<repo>/`, a custom domain, or a
 * preview deploy.
 *
 * Hoisted out of the config object because `head` needs it too: VitePress rewrites `base` into
 * markdown links and theme assets, but NOT into raw `head` tags — a `href: "/favicon.svg"` there
 * would 404 on any non-root base.
 */
const base = process.env.DOCS_BASE ?? "/";

export default defineConfig({
  title: "eufy-sdk",
  description: "Host-facing usage guides for the eufy SDK. Independent and unofficial.",
  base,
  /**
   * Tab-bar icon. SVG-only on purpose: the mark is a vector, and a single color-scheme-aware file
   * (see public/favicon.svg) covers both light and dark tab bars without shipping a raster pair.
   * Safari has no SVG-favicon support and falls back to /favicon.ico, which this site does not
   * serve — Safari tabs therefore show no icon until a raster fallback is added.
   */
  head: [["link", { rel: "icon", type: "image/svg+xml", href: `${base}favicon.svg` }]],
  // Repo prose that happens to sit under docs/ is not a page.
  srcExclude: ["**/README.md"],
  cleanUrls: true,
  lastUpdated: true,
  // Fail the build on a broken internal link (dead cross-link / renamed page). CI catches drift.
  ignoreDeadLinks: false,
  themeConfig: {
    // Nav-bar mark, beside the site title. Same braces mark as the home hero; the light/dark pair is
    // needed because the wordmark glyph is near-black on light and white on dark.
    logo: { light: "/logo.svg", dark: "/logo-dark.svg", alt: "eufy-sdk" },
    // Include h3 in the "On this page" outline — pages like the device gallery have one h2 and many
    // h3 family sections, which the default (h2-only) outline would leave empty.
    outline: [2, 3],
    nav: [{ text: "API", link: "/api/" }],
    sidebar: {
      // API reference pages get the TypeDoc-generated tree; everything else gets the guide sidebar.
      "/api/": [{ text: "API reference", link: "/api/" }, ...typedocSidebar],
      "/": [
        {
          // The guide pages land with the source move; this scaffold ships the landing page and the
          // generated reference alone.
          text: "Reference",
          items: [{ text: "API reference", link: "/api/" }],
        },
      ],
    },
    search: { provider: "local" },
    socialLinks: [
      { icon: "github", link: "https://github.com/mega-yfue/eufy-sdk" },
      { icon: "discord", link: "https://discord.gg/5wjQ2asb64" },
    ],
    footer: {
      message:
        "Independent and unofficial. Not affiliated with, endorsed by, or sponsored by " +
        "Anker Innovations or eufy. &quot;eufy&quot; and &quot;Anker&quot; are trademarks of their " +
        "respective owners. Use responsibly — rapid or failed logins can trigger captcha or " +
        "temporary cooldowns.",
    },
  },
});
